#GUI
MARGIN_TOP = 30
MARGIN_LEFT = 30
MARGIN_RIGHT = 30
MARGIN_BOTTOM = 30

RECT_BORDER = 1

SHOP_BUTTON_WIDTH = 150
SHOP_BUTTON_HEIGHT = 60
END_TURN_BUTTON_WIDTH = 150
END_TURN_BUTTON_HEIGHT = 50
PLAYER_INFO_BOX_WIDTH = 300
PLAYER_INFO_BOX_HEIGHT = 200

#GAME SETTINGS
PLAYER_AMOUNT = 4
START_BALANCE = 20
